# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37a08b0e3db72348254cadea3191fa974b21aa52bf0b20951e47781b9b8588358910792bd701167cf1674f32591c8624d21702481202b5c8d4a4712727bdb0fc

test:
  secret_key_base: 22b84a1785a908d9d3b298ec465621a7a8da545b40b231ce525c085266bbfa46ba475beb4f4325ffef2aa3737e47588d5c282c8906b06a6f4819220047ec0e40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
